class Audio {
  int _id;
  String _fileName;
  String _author;
  String _label;
  String _type;
  DateTime _date;

  Audio(this._id, this._fileName, this._author, this._label, this._type, this._date);

  static List<Audio> inserts = [
    Audio(1, "Abraham Weintraub - odeio, odeio, odeio short.mp3", "Abraham Weintraub", "Odeio, odeio, odeio", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(2, "ADY - oh não mais um crime de responsabilidade.mp3", "ADY", "Mais um crime", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(3, "Aham sei short.mp3", "", "Aham, sei", "INSERT", DateTime.parse("2021-03-01")),
    Audio(4, "Alborgeti - Que Merda Hein  MEME short.mp3", "Alborgeti", "Que merda hem", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(5, "Away - nao fode mermão short.mp3", "Away", "Não fode mermão", "INSERT", DateTime.parse("2021-03-01")),
    Audio(6, "Away - Para com essa porra aí mermão short.mp3", "Away", "Pára com essa porra", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(7, "BENDER Ahh, agora eu entendi short.mp3", "Bender", "Ah! Agora eu entendi", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(8, "Boldo - Carrralho caralho.mp3", "Boldo", "Carrralho caralho", "INSERT", DateTime.parse("2021-03-01")),
    Audio(9, "Boldo - Deixa com a cara magoada.mp3", "Boldo", "Deixa com a cara magoada", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(10, "Boldo - Esse é o boldo bão.mp3", "Boldo", "Esse é o boldo bão", "INSERT", DateTime.parse("2021-03-01")),
    Audio(11, "Boldo - Muito bom, muito bom.mp3", "Boldo", "Muito bom, muito bom", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(12, "Boldo - Parece até que um helicóptero pousou em cima da tua cara.mp3", "Boldo", "Helicóptero", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(
        13, "Boldo - Puta que pariu marquinho.mp3", "Boldo", "PQP, Marquinho", "INSERT", DateTime.parse("2021-03-01")),
    Audio(14, "Boldo - Que boldo bão.mp3", "Boldo", "Que boldo bão", "INSERT", DateTime.parse("2021-03-01")),
    Audio(15, "Bolsonaro - E daí.mp3", "Bolsonaro", "E daí?", "INSERT", DateTime.parse("2021-03-01")),
    Audio(16, "Bolsonaro - Eu não errei nenhuma.mp3", "Bolsonaro", "Eu não errei nenhuma", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(17, "Bolsonaro - Lamento, quer que eu faça o que.mp3", "Bolsonaro", "Lamento, quer q eu faça oq?", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(18, "Bolsonaro - Não tem como não dar errado vai dar errado.mp3", "Bolsonaro", "Ñ tem com ñ dar errado",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(19, "Bolsonaro - Porra.mp3", "Bolsonaro", "Porra", "INSERT", DateTime.parse("2021-03-01")),
    Audio(20, "Bolsonaro - Problemas.mp3", "Bolsonaro", "Problemas", "INSERT", DateTime.parse("2021-03-01")),
    Audio(21, "Bolsonaro - Será que eu tô errando ao falar isso daí.mp3", "Bolsonaro", "Será que eu tô errando?",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(22, "Bonitinha mas ordinária - É mentira dele meme short.mp3", "", "É mentira dele", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(23, "Bonitinha mas ordinária - Mentira.mp3", "", "Mentira", "INSERT", DateTime.parse("2021-03-01")),
    Audio(24, "BORA (Bam Bam).mp3", "Bam Bam", "Bora", "INSERT", DateTime.parse("2021-03-01")),
    Audio(25, "Boulos Porra short.mp3", "Boulos", "Porra!", "INSERT", DateTime.parse("2021-03-01")),
    Audio(26, "Brizola - Filhotes da ditadura.mp3", "Brizola", "Filhotes da ditadura", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(27, "Caetano - Não short.mp3", "Caetano", "Não", "INSERT", DateTime.parse("2021-03-01")),
    Audio(28, "Caetano - Que loucura, que coisa absurda short.mp3", "Caetano", "Que loucura", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(29, "CARLA BORA - Bora.mp3", "Carla", "Bora", "INSERT", DateTime.parse("2021-03-01")),
    Audio(30, "Carmina burana trecho.mp3", "Carmina Burana", "Carmina Burana", "INSERT", DateTime.parse("2021-03-01")),
    Audio(31, "Choque de Cultura - Cabô cabô cabô já tá desvirtuando já short.mp3", "Choque", "Ta desvirtuando já",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(32, "Choque de Cultura - Falo com tranquilidade.mp3", "Choque", "Falo com tranquilidade", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(33, "Choque de Cultura - Renan - é Paradoxo que chama isso aí.mp3", "Choque", "Paradoxo", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(34, "Choque de Cultura - Renan - Vamos fazer essa crítica aí.mp3", "Choque", "Vamos fazer essa crítica aí",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(35, "Choque de Cultura - Rogerinho - Aqui tem informação.mp3", "Choque", "Aqui tem informação", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(36, "CHOQUE DE CULTURA - Rogerinho Às vezes o ódio é a única emoção possível short.mp3", "Choque",
        "Ódio é a única opção", "INSERT", DateTime.parse("2021-03-01")),
    Audio(37, "Choque de cultura - Rogerinho - Não vamos falar de pornô aqui não.mp3", "Choque",
        "Não vamos falar de pornô", "INSERT", DateTime.parse("2021-03-01")),
    Audio(38, "Choque de Cultura - Rogerinho - Ó a informação aí.mp3", "Choque", "Olha a informação aí", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(39, "Cidade Oculta - Você fala isso porque é a putinha do bozo.mp3", "Cidade Oculta", "Putinha do Bozo",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(40, "Ciro Gomes  - Atenção Paulo Guedes.mp3", "Ciro Gomes", "Atenção, Paulo Guedes", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(41, "Ciro Gomes - Conspirador filho da puta.mp3", "Ciro Gomes", "Conspirador, FDP", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(42, "CIRO GOMES - Paulo Guedes mentiroso tá enganando a rapaeada paulo guedes.mp3", "Ciro Gomes",
        "Paulo Guedes mentiroso", "INSERT", DateTime.parse("2021-03-01")),
    Audio(43, "Ciro Gomes - Que isso, francamente.mp3", "Ciro Gomes", "Que isso, francamente", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(44, "Ciro Gomes - Veja bem, se eu estiver errado me corrija.mp3", "Ciro Gomes", "Veja bem", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(45, "com certeza cerginho da perera nunes short.mp3", "Serginho", "Com certeza", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(46, "COMUNISTA DO INFERNO meme.mp3", "Doida varrida", "Comunista do inferno", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(47, "COMUNISTA MEME.mp3", "Doida varrida", "Comunista", "INSERT", DateTime.parse("2021-03-01")),
    Audio(48, "Costinha - Se fudeu short.mp3", "Costinha", "Se fudeu", "INSERT", DateTime.parse("2021-03-01")),
    Audio(49, "Craque Neto - E cuidado com a cueca hein, cuidado com a cueca.mp3", "Craque Neto",
        "Cuidado com a cueca, hem", "INSERT", DateTime.parse("2021-03-01")),
    Audio(50, "Drauzio - É verdade quer dizer as vezes não meme short.mp3", "Dráuzio", "É verdade", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(51, "Dráuzio - procura um psiquiatra, você não tá legal.mp3", "Dráuzio", "Procura um psiquiatra", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(52, "Fernando Collor - Isso é uma mentira uma pantomima uma patuscada short.mp3", "Collor",
        "Pantomima, patuscada", "INSERT", DateTime.parse("2021-03-01")),
    Audio(53, "Fernando Collor - três vezes dizendo que é mentira.mp3", "Collor", "Três vezes que é mentira", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(54, "Fred cê tá falando sério.mp3", "Frec", "Vc ta falando sério?", "INSERT", DateTime.parse("2021-03-01")),
    Audio(55, "Futurama - Então tudo bem short.mp3", "Futurama", "Então tudo bem", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(56, "General Mourão Bom Dia short.mp3", "Mourão", "Bom dia", "INSERT", DateTime.parse("2021-03-01")),
    Audio(57, "Gustavo mendes dilma todo mundo se fudeu.mp3", "Gustavo Mendes", "Todo mundo se fudeu", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(58, "Hassum - Nem fodendo.mp3", "Hassum", "Nem fodendo", "INSERT", DateTime.parse("2021-03-01")),
    Audio(59, "Hassum - PUTA QUE PARIU.mp3", "Hassum", "Puta que pariu", "INSERT", DateTime.parse("2021-03-01")),
    Audio(60, "Ivete Sangalo - Chupa Toda short meme.mp3", "Ivete Sangalo", "Chupa toda", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(61, "Leo Stronda Porra.mp3", "Leo Stronda", "Porra", "INSERT", DateTime.parse("2021-03-01")),
    Audio(62, "Mermão na moral short.mp3", "Futurama", "Mermão na moral", "INSERT", DateTime.parse("2021-03-01")),
    Audio(63, "Michel Temer - Pigarro.mp3", "Michel Temer", "Pigarro", "INSERT", DateTime.parse("2021-03-01")),
    Audio(64, "Michel Temer - Tem que pedir uma pastilha.mp3", "Michel Temer", "Pastilha", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(65, "MIDCAST - Teu cu.mp3", "Midcast", "Teu cu", "INSERT", DateTime.parse("2021-03-01")),
    Audio(66, "Mourão - Essa conta irá para as Forças Armadas trecho short.mp3", "Mourão",
        "Conta irá para as Forças Armadas", "INSERT", DateTime.parse("2021-03-01")),
    Audio(67, "Mourão - Você é muito mais físico do que intelectual short.mp3", "Mourão", "Muito mais físico", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(68, "Neto - Cês tão de brincadeira.mp3", "Neto", "Vocês estão de brincadeira", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(69, "Neto - Vocês estão de sacanagem short.mp3", "Neto", "Vocês estão de sacanagem", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(70, "Olavo de Carvalho  Olavão Porra.mp3", "Olavo", "Porra", "INSERT", DateTime.parse("2021-03-01")),
    Audio(71, "Olavo - Porrrrra.mp3", "Olavo", "Porrrrra", "INSERT", DateTime.parse("2021-03-01")),
    Audio(72, "Opaíó - Tomar no cu rapaz.mp3", "Opaíó", "Tomar no cu, rapaz", "INSERT", DateTime.parse("2021-03-01")),
    Audio(73, "Pazuello - É simples assim, um manda e o outro obedece.mp3", "Pazuello", "Um manda e o outro obedece",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(74, "Pazuello - Não tem o que fazer.mp3", "Pazuello", "Não tem o que fazer", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(75, "Pazuello - Que que cê vai fazer nada.mp3", "Pazuello", "Oq c vai fazer? Nada.", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(76, "Queima quengaral wooo short.mp3", "", "Queima quengaral", "INSERT", DateTime.parse("2021-03-01")),
    Audio(77, "Que merda hein short.mp3", "Marinho", "Que merda hem", "INSERT", DateTime.parse("2021-03-01")),
    Audio(78, "Que porra é essa batata.mp3", "", "Que porra é essa, Batata", "INSERT", DateTime.parse("2021-03-01")),
    Audio(79, "Quercia - É mentira, é tudo mentira.mp3", "Quercia", "É tudo mentira", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(80, "Quercia - Mentiroso e caluniador, caluniador e mentiroso .mp3", "Quercia", "Mentiroso e caluniador",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(81, "Regina Duarte - Pum.mp3", "Regina Duarte", "Pum", "INSERT", DateTime.parse("2021-03-01")),
    Audio(82, "Reinaldo Azevedo - É mentira.mp3", "Reinaldo Azevedo", "É mentira", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(83, "Reinaldo Azevedo - Parte Terminal do Aparelho Digestivo.mp3", "Reinaldo Azevedo", "Aparelho digestivo",
        "INSERT", DateTime.parse("2021-03-01")),
    Audio(84, "Sabe que você é muito petulante.mp3", "", "Você é muito petulante", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(85, "Saiddy Bamba - Vai chorar é vai chorar é chore na minha.mp3", "Saiddy Bamba", "Chore na minha", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(86, "SALLES - E ir passando a boiada.mp3", "Salles", "Passando a boiada", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(87, "Será mesmo.mp3", "", "Será mesmo", "INSERT", DateTime.parse("2021-03-01")),
    Audio(88, "Silas Malafaia - É por isso que Deus te escolheu.mp3", "Silas Malafaia", "Deus te escolheu", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(89, "Silas Malafaia - Eu tenho pena short.mp3", "Silas Malafaia", "Eu tenho pena", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(90, "Silas Malafaia - gente que vive tanto na mentira que faz dela a sua verdade.mp3", "Silas Malafaia",
        "Gente que vive tanto na mentira", "INSERT", DateTime.parse("2021-03-01")),
    Audio(91, "Silas Malafaia - Mentiroso sem vergonha vai pro inferno short.mp3", "Silas Malafaia",
        "Mentiroso sem vergonha", "INSERT", DateTime.parse("2021-03-01")),
    Audio(92, "Silas Malafaia - Não seja um mentiroso short.mp3", "Silas Malafaia", "Não seja um mentiroso", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(93, "Silas Malafaia - Nunca vi tu é burro cara.mp3", "Silas Malafaia", "Tu é burro cara", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(94, "Temer - Não renunciarei short.mp3", "Temer", "Não renunciarei", "INSERT", DateTime.parse("2021-03-01")),
    Audio(95, "Trote Luiz Pareto - TELERJ meme mas que filho da puta olhaí veja você.mp3", "Luiz Pareto",
        "Mas que filho da puta", "INSERT", DateTime.parse("2021-03-01")),
    Audio(96, "Trote Pareto - Calma filha da puta calma.mp3", "Luiz Pareto", "Calma, filha da puta", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(97, "Tu tava fora do brasil irmão short.mp3", "", "Tava fora do brasil, irmão?", "INSERT",
        DateTime.parse("2021-03-01")),
    Audio(98, "Ulysses Guimarães - Temos ódio à ditadura, ódio e nojo.mp3", "Ulysses Guimarães",
        "Temos ódio à ditadura", "INSERT", DateTime.parse("2021-03-01")),
    Audio(99, "Xaropinho - Rapaz short.mp3", "Xaropinho", "Rapaz", "INSERT", DateTime.parse("2021-03-01")),
    Audio(100, "Ady - A pandemia ainda não acabou, porra.mp3", "Ady", "A pandemia não acabou, porra", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(101, "Agora tu aguenta.mp3", "", "Agora tu aguenta", "INSERT", DateTime.parse("2021-05-05")),
    Audio(102, "Ai que delícia - meme short.mp3", "", "Ai que delícia", "INSERT", DateTime.parse("2021-05-05")),
    Audio(103, "Alborgetti - Ah Vá a merda porra short meme.mp3", "Alborghetti", "Vá a merda", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(104, "Alborghetti - Tá uma merda esse país.mp3", "Alborghetti", "Tá uma merda esse país", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(105, "A mãe copiloto - celera bem, acelera short meme.mp3", "Mãe copilota", "Celera bem", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(106, "Atenção é agora que o bicho vai pegar short meme.mp3", "", "Agora o bicho vai pegar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(107, "Até o final tu vai bancar esse merda lá seu merda.mp3", "", "Até o final, vai bancar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(108, "ÁTILA IAMARINO - Não tem condições.mp3", "Átila", "Não tem condições", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(109, "ÁTILA IAMARINO - Que que eu posso tomar você pode tomar cuidado e vacina.mp3", "Átila",
        "Pode tomar cuidado, vacina…", "INSERT", DateTime.parse("2021-05-05")),
    Audio(110, "ÁTILA IAMARINO - Você vai morrer (resumo da live).mp3", "Átila", "Você vai morrer", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(111, "Bandido de Cristo tem muita fé em Deus.mp3", "", "Bandido de Cristo", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(112, "Boldo - é de quanto é de quanto.mp3", "Boldo", "É de quanto?", "INSERT", DateTime.parse("2021-05-05")),
    Audio(113, "Bolsonaro - A coisa é séria pessoal.mp3", "Bolsonaro", "A coisa é séria, pessoal", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(114, "BOLSONARO - Ah nhem nhem nhem nhem olha o problema aí.mp3", "Bolsonaro", "nhem nhem nhem", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(115, "Bolsonaro - ah o o cara quem fala disso eu não sou coveiro tá ok.mp3", "Bolsonaro", "Não sou coveiro",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(116, "Bolsonaro - a imprensa mundial é de esquerda.mp3", "Bolsonaro", "A imprensa é de esquerda", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(117, "Bolsonaro - duas letras PF é polícia federal ô cara.mp3", "Bolsonaro", "Duas letras: PF", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(118, "Bolsonaro - É coisa de viado o que ele estão fazendo.mp3", "Bolsonaro", "Coisa de viado", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(119, "Bolsonaro - Enfrentar como homem, pô, e não como moleque.mp3", "Bolsonaro", "Enfrentar como um homem",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(120, "Bolsonaro - Eu sou favorável à tortura, tu sabe disso.mp3", "Bolsonaro", "Favorável à tortura",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(121, "Bolsonaro - Finalzinho de pandemia.mp3", "Bolsonaro", "Finalzinho de pandemia", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(122, "Bolsonaro - Ganhou porra.mp3", "Bolsonaro", "Ganhou, porra", "INSERT", DateTime.parse("2021-05-05")),
    Audio(123, "Bolsonaro - Jacaré.mp3", "Bolsonaro", "Jacaré", "INSERT", DateTime.parse("2021-05-05")),
    Audio(124, "Bolsonaro - Mas não quero polemizar esse assunto aí.mp3", "Bolsonaro", "Não quero polemizar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(125, "Bolsonaro - Me chama de corrupto porra.mp3", "Bolsonaro", "Me chama de corrupto", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(126, "Bolsonaro não pode ser presidente da república.mp3", "Bolsonaro", "Não pode ser presidente", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(127, "Bolsonaro - No que depender de mim nunca teremos lockdown.mp3", "Bolsonaro", "Nunca teremos lockdown",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(128, "Bolsonaro - O caos vem aí.mp3", "Bolsonaro", "O caos vem aí", "INSERT", DateTime.parse("2021-05-05")),
    Audio(129, "Bolsonaro - Ô cara ô cara.mp3", "Bolsonaro", "Ô cara", "INSERT", DateTime.parse("2021-05-05")),
    Audio(130, "Bolsonaro - Paralelepípedo de crack.mp3", "Bolsonaro", "Parelepípedo de crack", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(131, "Bolsonaro - Porra Porras.mp3", "Bolsonaro", "Porra, porras", "INSERT", DateTime.parse("2021-05-05")),
    Audio(132, "Bolsonaro - Pra mídia, o vírus sou eu.mp3", "Bolsonaro", "O vírus ou eu", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(133, "BOLSONARO - Sem o viés ideológico.mp3", "Bolsonaro", "Sem o viés ideológico", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(134, "Bolsonaro - Tá sendo superdimensionado o poder destruidor desse vírus.mp3", "Bolsonaro",
        "Superdimensionando o vírus", "INSERT", DateTime.parse("2021-05-05")),
    Audio(135, "Bolsonaro - Tem que deixar de ser um país de maricas pô.mp3", "Bolsonaro", "País de maricas", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(136, "Bolsonaro - Tem que trabalhar.mp3", "Bolsonaro", "Tem que trabalhar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(137, "Bolsonaro - Uma crise uma pequena crise né.mp3", "Bolsonaro", "Uma pequena crise", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(138, "BRUNO HENRIQUE - Porque nós tamos em outro patamar.mp3", "Bruno Henrique", "Outro patamar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(139, "Catra - Demorou.mp3", "Catra", "Demorou", "INSERT", DateTime.parse("2021-05-05")),
    Audio(140, "CAUE MOURA - O Jovem tem que acabar.mp3", "Cauê Moura", "O jovem tem que acabar", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(141, "Cidinho E Doca - Fé em deus dj meme short.mp3", "Cidinho e Doca", "Fé em Deus", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(142, "Ciro Gomes - Paulo Guedes onde é que funcionou esse ideario.mp3", "Ciro Gomes", "Onde é que funcionou?",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(143, "Collor - Um devaneio, um sonho de uma noite de verão.mp3", "Collor", "Devaneio, sonho de uma noite…",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(144, "Como assim eu não entendi meme short.mp3", "", "Não entendi", "INSERT", DateTime.parse("2021-05-05")),
    Audio(145, "Craque Neto - Pá aplica numa bunda pá aplica na outra.mp3", "Neto", "Pá! Aplica numa bunda", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(146, "Datena - Gol do presidente Bolsonaro.mp3", "Datena", "Gol do presidente", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(147, "Datena - Me pareceu uma grande marmelada.mp3", "Datena", "Grande marmelada", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(148, "De cair o cu da bunda short meme.mp3", "", "De cair o cu da bunda", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(149, "Dilma - Vai todo mundo perder.mp3", "Dilma", "Vai todo mundo perder", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(150, "Doidão do Napster - Vai tomar no cu, no cu, no cu eu não tô doido não.mp3", "Doidão do Napster",
        "Vai tomar no c*", "INSERT", DateTime.parse("2021-05-05")),
    Audio(151, "Dráuzio - As pessoas não tem consciência disso.mp3", "Dráuzio", "Consciência disso", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(152, "Eduardo Cunha - Que Deus tenha misericórdia dessa nação.mp3", "Eduardo Cunha",
        "Que Deus tenha misericórida", "INSERT", DateTime.parse("2021-05-05")),
    Audio(153, "Eita porra do caralho agora fudeu.mp3", "", "Eita p*rra do c*ralho", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(154, "É O TCHAN - Loop.mp3", "Tchan", "Loop do Tchan", "INSERT", DateTime.parse("2021-05-05")),
    Audio(155, "Ernesto Araújo - Se isso faz de nós um pária internacional então que sejamos esse pária.mp3",
        "Ernesto Araújo", "Pária internacional", "INSERT", DateTime.parse("2021-05-05")),
    Audio(156, "Eu fico muito triste com uma notícia dessas filha da puta fogos short.mp3", "",
        "Muito triste com uma notícia dessa", "INSERT", DateTime.parse("2021-05-05")),
    Audio(157, "Eu tô passada, chocada.mp3", "", "Eu tô passada, chocada", "INSERT", DateTime.parse("2021-05-05")),
    Audio(158, "Falha de Cobertura - Cerginho da Pereira Nunes - Doidera.mp3", "", "Doideira", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(159, "Galo Cego - Nada a ver irmão.mp3", "Galo Cego", "Nada a ver, irmão", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(160, "General Santos Cruz - O responsável é o presidente.mp3", "Gen. Santos Cruz",
        "O responsável é o presidente", "INSERT", DateTime.parse("2021-05-05")),
    Audio(161, "Gilmar Mendes - aha uhu o Fachin é nosso.mp3", "Gilmar Mendes", "O Fachin é nosso", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(162, "Gilmar Mendes - Com a devida vênia.mp3", "Gilmar Mendes", "Com a devida vênia", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(163, "Gilmar Mendes - Eu já disse aqui.mp3", "Gilmar Mendes", "Eu já disse aqui", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(164, "Glauber Braga - Ladrão e Corrompido.mp3", "Glauber Braga", "Ladrão e corrompido", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(165, "Glauber Braga - Ladrão.mp3", "Glauber Braga", "Ladrão", "INSERT", DateTime.parse("2021-05-05")),
    Audio(166, "Heleno - Se gritar pega centrão short meme.mp3", "Heleno", "Se gritar pega centrão", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(167, "Jacquin -  Cala a boca short.mp3", "Jacquin", "Cala a boca", "INSERT", DateTime.parse("2021-05-05")),
    Audio(172, "Lula - Alô.mp3", "Lula", "Alô", "INSERT", DateTime.parse("2021-05-05")),
    Audio(173, "Lula - Chupa que a cana é doce meu filho.mp3", "Lula", "Chupa que a cana é doce", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(174, "Lula - Eu vou lhe dizer uma coisa pra ficar com a minha consciência leve.mp3", "Lula",
        "Consciência leve", "INSERT", DateTime.parse("2021-05-05")),
    Audio(175, "Lula - O isolamento, máscara, álcool em gel.mp3", "Lula", "Isolamento, máscara e álcool", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(176, "Malafaia - JAIR MESSIAS BOLSONARO.mp3", "Malafaia", "Jair Messias Bolsonaro", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(177, "Mourão - Coronel Brilhante Ustra Meu herói short meme.mp3", "Mourão", "Ustra, meu herói", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(178, "Não é fanatismo, eu quero morrer junto do senhor.mp3", "Apoiadora", "Eu quero morrer com o senhor",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(179, "Não sei meme short exaltado.mp3", "", "Não sei", "INSERT", DateTime.parse("2021-05-05")),
    Audio(180, "Narcisa Tamborindeguy - Ai que loucura.mp3", "Narcisa Tamborindeguy", "Ai que loucura", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(181, "Natália Pasternak - É um pedaço de pano no rosto, é uma porra de um pedaço de pano na cara.mp3",
        "Natália Pasternak", "Pedaço de pano no rosto", "INSERT", DateTime.parse("2021-05-05")),
    Audio(182, "Nhonho olha ele olha ele short.mp3", "Nhonho", "Olha ele", "INSERT", DateTime.parse("2021-05-05")),
    Audio(183, "Onyx - Alguém consegue fazer o lockdown dos insetos.mp3", "Onyx", "Lockdown dos insetos", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(184, "O sangue de jesus tem poder short meme.mp3", "", "Sangue de Jesus tem poder", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(185, "Osório - Flávio Bolsonaro desmaio - Não dá pra continuar, tá passando mal short.mp3", "Osório",
        "Não dá pra continuar", "INSERT", DateTime.parse("2021-05-05")),
    Audio(186, "Passando pano pro Bolsonaro.mp3", "", "Passando pano", "INSERT", DateTime.parse("2021-05-05")),
    Audio(187, "Pazuello - O cu dilatado.mp3", "Pazuello", "O c* dilatado", "INSERT", DateTime.parse("2021-05-05")),
    Audio(188, "Pedro Dória - Eles mentem mentem na cara dura mentem sem ter vergonha de mentir.mp3", "Pedro Dória",
        "Eles mentem", "INSERT", DateTime.parse("2021-05-05")),
    Audio(189, "Pedro Dória - General da Ativa.mp3", "Pedro Dória", "General da ativa", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(190, "Pedro Pedreira (Pedra 90) - Não delira, não patina no omelete.mp3", "Pedro Pedreira",
        "Não delira, não patina", "INSERT", DateTime.parse("2021-05-05")),
    Audio(191, "Por que será short meme.mp3", "Galvão", "Por que será?", "INSERT", DateTime.parse("2021-05-05")),
    Audio(192, "Porra é isso.mp3", "", "Porra! É isso", "INSERT", DateTime.parse("2021-05-05")),
    Audio(193, "Qual foi.mp3", "", "Qual foi?", "INSERT", DateTime.parse("2021-05-05")),
    Audio(
        194, "Queima quengaral só grito.mp3", "", "Grito do queima quengaral", "INSERT", DateTime.parse("2021-05-05")),
    Audio(195, "Roberto Jefferson - Vossa Excelência provoca em mim os instintos mais primitivos short meme.mp3",
        "Roberto Jefferson", "Provoca em mim os instintos…", "INSERT", DateTime.parse("2021-05-05")),
    Audio(196, "Rogério Skylab - Dedo no Cu e Gritaria - short.mp3", "Skylab", "Dedo no c* e gritaria", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(197, "SAIDDY BAMBA - Não não não não short.mp3", "Saiddy Bamba", "Não, não, não, não…", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(198, "SAIDDY BAMBA - Sim, sim, sim, sim, sim - short meme.mp3", "Saiddy Bamba", "Sim, sim, sim, sim…",
        "INSERT", DateTime.parse("2021-05-05")),
    Audio(199, "Sai desgraça, eu quero dormir porra short meme.mp3", "", "Sai desgraça, eu quero dormir", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(200, "Sérgio Mallandro - Yehyeh yeah yeah ié ié rááá rá.mp3", "Sérgio Malandro", "Yeah Yeah", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(201, "Silvio Santos -  Essa não é boa , ninguém deu risada.mp3", "Silvio Santos", "Essa não é boa", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(202, "Tite - Fala muito!.mp3", "Tite", "Fala muito", "INSERT", DateTime.parse("2021-05-05")),
    Audio(204, "Ulisses - Traidor da Constituição é traidor da pátria.mp3", "Ulisses Guimarães",
        "Traidor da constituição", "INSERT", DateTime.parse("2021-05-05")),
    Audio(205, "Valdomiro - Eu estou no limite brasil.mp3", "Valdomiro", "Estou no limite, Brasil", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(206, "Valdomiro - eu não estou suportando mais.mp3", "Valdomiro", "Não estou suportando", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(207, "Valdomiro - Eu não suporto mais.mp3", "Valdomiro", "Eu não suporto mais", "INSERT",
        DateTime.parse("2021-05-05")),
    Audio(
        208, "Viajou, passeou qual foi.mp3", "", "Viajou, passeou, qual foi?", "INSERT", DateTime.parse("2021-05-05")),
    Audio(209, "Xô drogado short meme.mp3", "", "Xõ, drogado", "INSERT", DateTime.parse("2021-05-05")),
    Audio(210, "Zé Gotinha - Olá meu nome é zé gotinha.mp3", "Zé Gotinha", "Meu nome é Zé Gotinha", "INSERT",
        DateTime.parse("2021-05-05")),
  ];

  int get id => _id;

  set id(int value) {
    _id = value;
  }

  String get fileName => _fileName;

  set fileName(String value) {
    _fileName = value;
  }

  String get author => _author;

  set author(String value) {
    _author = value;
  }

  String get label => _label;

  set label(String value) {
    _label = value;
  }

  String get type => _type;

  set type(String value) {
    _type = value;
  }

  DateTime get date => _date;

  set date(DateTime value) {
    _date = value;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Audio &&
          runtimeType == other.runtimeType &&
          _id == other._id &&
          _fileName == other._fileName &&
          _author == other._author &&
          _label == other._label &&
          _type == other._type &&
          _date == other._date;

  @override
  int get hashCode =>
      _id.hashCode ^ _fileName.hashCode ^ _author.hashCode ^ _label.hashCode ^ _type.hashCode ^ _date.hashCode;
}
